version: '3.8'

services:
  db:
    image: mysql:8.0
    #command:
    #  --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: programs
      MYSQL_USER: mysql
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local