if db_id('programs') IS NULL
    CREATE DATABASE programs;

GO

USE programs;

GO

CREATE TABLE IF NOT EXISTS programs.ProgramEntries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, submissionDate DATE NOT NULL, originalName MEDIUMTEXT NOT NULL, program LONGTEXT NOT NULL, loc INT NOT NULL, frontend MEDIUMTEXT NOT NULL, originalVerifier MEDIUMTEXT NOT NULL, siliconResJSON MEDIUMTEXT NOT NULL, carbonResJSON MEDIUMTEXT NOT NULL, argsJSON MEDIUMTEXT NOT NULL, siliconPhaseRuntimesJSON MEDIUMTEXT NOT NULL, carbonPhaseRuntimesJSON MEDIUMTEXT NOT NULL, programPrintJSON LONGTEXT NOT NULL, parseSuccess BOOLEAN NOT NULL, hasPreamble BOOLEAN NOT NULL);
CREATE TABLE IF NOT EXISTS programs.UserSubmissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, originalName MEDIUMTEXT NOT NULL, program LONGTEXT NOT NULL, loc INT NOT NULL, frontend MEDIUMTEXT NOT NULL, argsJSON MEDIUMTEXT NOT NULL, originalVerifier MEDIUMTEXT NOT NULL, success BOOLEAN NOT NULL);